version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: c:\projects\uacme
build:
  project: Source/uacme.sln
  verbosity: normal
artifacts:
  - path: ".\output\x64\Release\*"
